### ISSUE TITLE
doesn't work if the repo in only local

### ISSUE THREAD

**Issue by mattetti** [defunkt/cijoe#1]
if the repo hasn't been yet pushed cijoe fails on:

```
def git_user_and_project
  Config.remote.origin.url.to_s.chomp('.git').split(':')[-1].split('/')[-2, 2]
end
```
- Matt

**Comment by defunkt** [comment]
It's kind of built to do a `git pull` and needs `origin`. Were you just playing around or do you want to use it on a local-only repo seriously?

**Comment by mattetti** [comment]
I was giving it a try with MacRuby which is still on svn and I was using git svn. I got it to work by creating a repo on github and make it the origin master of my git svn project.

**Comment by defunkt** [comment]
Closing for now, unless someone wants to send a patch :)
