### ISSUE TITLE
passing through environment vars that contain ` characters causes failures

### ISSUE THREAD

**Issue by tmm1** [defunkt/cijoe#13]
http://github.com/defunkt/cijoe/commit/1eca495bed36940e3d7fe8855116ef123404a09c

causes issues when OUTPUT contains a ` character. I patched cijoe to just use ENV instead:

http://github.com/tmm1/cijoe/commit/7aa426d15ea51e7f1446310ec9a279522f3df1b0

**Comment by defunkt** [comment]
Merged, thanks!
