### ISSUE TITLE
Magic submodule handling

### ISSUE THREAD

**Issue by kerinin** [defunkt/cijoe#14]
It would be really cool if cijoe checked for submodules and updated them before running tests.  I'm setting up the after-reset hook to do this, but it's a pain in the butt.

**Comment by defunkt** [comment]
What's your `after-reset` hook look like?

**Comment by kerinin** [comment]
```
cd <repo dir>
git submodule init
git submodule update
```

Nothing special, just inits and updates the repos.  I put the init in there in case I added submodules.  Not sure how this would handle removing submodules though

**Comment by docteurklein** [comment]
You could maybe try 

git submodule update --init --recursive

in you after-reset hook,but that do not resolve the problem.
