### ISSUE TITLE
concurrent push - just one build

### ISSUE THREAD

**Issue by fritzek** [defunkt/cijoe#15]
two developers are pushing nearly the same time (let say a minute diff, but build still running). the second push never gets built. is there a way to "queue" those concurrent requests?
thx in advance
Fritzek

**Comment by defunkt** [comment]
I almost feel like this should stop the build and start the newer build, so it's not wasting time running tests that have become outdated. What do you think?

**Comment by fritzek** [comment]
You're right. We talk about pushes to the same branch and the newest push should be preferred. But e.g. in my case I start a server inside the build script. If you kill the current build the server will still run. For this reason we should make a note in the readme, that build scripts starting a server should kill previously started server before starting a new one. Should be no problem because the former pid file is present and can be checked. If pid file is there - kill process (here is a sh example:
    # make sure server isn't running from a previous build
    if [ -f 'tmp/pids/server.pid' ]
    then
      kill -9 `cat tmp/pids/server.pid`
      rm tmp/pids/server.pid
    fi

**Comment by defunkt** [comment]
Oh yeah, you're right. We spin up memcached instances to test against in our tests, too.

**Comment by fritzek** [comment]
what do you think about a kind of "queueing" - get the second payload, save it and wait until the first build is passed? if in the meantime another payload comes in the first, waiting one will be deleted. so we don't care about any running processes, servers or other stuff and leave it to the build process. just handle incoming payloads.

**Comment by defunkt** [comment]
I like it.

**Comment by fritzek** [comment]
hope you've seen my pull request for solving this issue. Would be nice to hear your comment about.

**Comment by defunkt** [comment]
Merged, thanks!
