### ISSUE TITLE
CIJoe#git_user_and_project raises an error when cijoe is configured as a gem using config.ru

### ISSUE THREAD

**Issue by technicalpickles** [defunkt/cijoe#16]
This one was really tricky to track down. I setup my project using the suggested config.ru, like so:

```
require 'rubygems' 
require 'cijoe'

use Rack::CommonLogger
CIJoe::Server.configure do |config|
   config.set :project_path, '/srv/cijoe/myproject'
   config.set :show_exceptions, true
   config.set :lock, true
end

run CIJoe::Server
```

But, I was seeing an error like this when running a config.ru under passenger, or even shotgun.

```
private method `split' called for nil:NilClass
/usr/lib/ruby/gems/1.8/gems/cijoe-0.3.0/lib/cijoe.rb: in git_user_and_project, line 143
```

The symptom here is that `Config.remote.origin.url.to_s` is returning empty string, so when you try to chomp a string off, you get nil, and nil can't be split.

Further investigation suggest the current directory was `/srv/cijoe/myproject`. The trick is that Config tries to cd into a directory, and bases it somewhere... but it tries to cd into `$project_path || File.join(File.dirname(__FILE__), '../../')`. If you were using the `cijoe` command line, you'd be fine, since it sets `$project_path`. Since the config.ru doesn't, it defaults to `../../`, which when installed as a gem, ends up being somewhere under `/usr`, and definitely is wrong.

The quick fix would be to just set `$project_path`, but that seems nasty. I'd hope that configuring the project_path would work as expected, so probably `CIJoe::Config` needs some more smarts to know about that configuration.

**Comment by shingara** [comment]
Yes you need define the $project_path global. So I made a branch in my fork (http://github.com/shingara/cijoe/tree/feature-avoid-project-path-global-variable) In this branch I avoid using $project_path So you can't avoid using it.

**Comment by defunkt** [comment]
Merged - thanks shingara!
