### ISSUE TITLE
Campfire API changes break integration

### ISSUE THREAD

**Issue by henrypoydar** [defunkt/cijoe#17]
The tinder 1.2.0 gem currently returns [] when querying for Campfire rooms.  So the room#speak method called within Joe fails.  Here's a quick fix using tinder 1.4.0:

http://github.com/hpoydar/cijoe/commit/b0819492b316109fa1fce2d8be6ae252b06021f3

I'll send a pull request too.

**Comment by defunkt** [comment]
Sweet! Merged, thanks.
