### ISSUE TITLE
CIJOE runs test in production env

### ISSUE THREAD

**Issue by gravis** [defunkt/cijoe#18]
Hi,

I have a weird behavior with CIJOE. When rake in invoked for the tests, it's loading the production environment instead of "test" or "cucumber". All logs are going to log/production.log, and tests are failing because of missing configurations in the production.rb file (of course).

the git/config contains :

```
[cijoe]
branch = develop
runner = /usr/bin/git submodule update --init && sudo rake gems:install && sudo rake gems:install RAILS_ENV=test && sudo rake gems:install RAILS_ENV=cucumber && rake db:migrate && rake -s
buildallfile = tmp/cijoe.txt
```

And if I run this command line with the user running cijoe, it's going fine.
Any idea ?
thanks

**Comment by defunkt** [comment]
`sudo` isn't going to let you pass through env variables like that.

Try http://www.hui-wang.info/2009/10/sudo-and-environment-variable/

We actually write a script:
    [cijoe]
            runner = .git/hooks/run-tests
            branch = master

`run-tests` sets up our environment, sudos, etc etc

**Comment by gravis** [comment]
sorry, I think I'm missing something here.
I'm telling, I have a different behavior in CIJOE and in command line.
Let's assume CIJOE is ran by cijoeusr.
If login as cijoeusr, and run 
    /usr/bin/git submodule update --init && sudo rake gems:install && sudo rake gems:install RAILS_ENV=test && sudo rake gems:install RAILS_ENV=cucumber && rake db:migrate && rake -s

everything is going just fine. Within CIJOE, the env is set to production, I think it has something to do with rack.
And BTW, I must have a special sudo :

```
Environment variables to be set for the command may also be passed on the command line in the form of VAR=value, e.g.  LD_LIBRARY_PATH=/usr/local/pkg/lib.
```

(from the sudo man).
thanks

**Comment by gravis** [comment]
I've put all my commands in a run-tests file, and do a 

```
echo $RAILS_ENV 
```

at the very beginning of the file. It displays "production". I think passenger is setting this by default.

**Comment by gravis** [comment]
Ok, turns out I can override the RAILS with export in the script, now it's working.
