### ISSUE TITLE
various fixes for master

### ISSUE THREAD

**Issue by tmm1** [defunkt/cijoe#19]
just fixed a bunch of bugs i ran into in http://github.com/tmm1/cijoe/compare/defunkt:master...master

most were caused due to our test suite generating a ton of output, which was causing all calls to git and hooks to fail. turns out there's a hard limit of 128k of data that can be passed to a subprocess via the argument list and environment variables, before exec starts failing with E2BIG

**Comment by defunkt** [comment]
merged and pushed as 0.5.0
