### ISSUE TITLE
rip err on install

### ISSUE THREAD

**Issue by softprops** [defunkt/cijoe#2]
This may be a rip issue or I may be retarded but I get this error (http://gist.github.com/163696) when trying to install with rip. There is a pretty good chance I am retarded.

**Comment by defunkt** [comment]
This is my fault. I just pushed out the newest version of Rip, 0.0.3, which fixes this. Can you try uninstalling then reinstalling the Rip gem?

Sorry about that.

**Comment by softprops** [comment]
heh. the new version of rip fixes the issue.
verified - http://gist.github.com/163703
