### ISSUE TITLE
support for local branch

### ISSUE THREAD

**Issue by ywen** [defunkt/cijoe#20]
Can we have support for local branch (the branch that just exists on your local, not on the remote)? Thanks

**Comment by ywen** [comment]
I know there is another closed issue for this. But I think as a lightweight CI server, it is important to support local branch, since we may run cc.rb as the central CI server, but cijoe as a local CI server. there are branches we just don't want to push to the remote, but do want to be run against a CI server. I may try to see if I can submit a patch for this, if I have time. Thanks

**Comment by defunkt** [comment]
We don't really use this, but patches are welcome.
