### ISSUE TITLE
Woes with bundler ?

### ISSUE THREAD

**Issue by gravis** [defunkt/cijoe#23]
Hi, 

we've switched to bundler (0.9) recently, and CIJOE doesn't seem to like it :

<pre>Using rake (0.8.7) from system gems
Using Saikuro (1.1.0) from system gems
Using SystemTimer (1.2) from bundler gems
Using abstract (1.0.0) from system gems
Using activesupport (2.3.8) from system gems
Using rack (1.1.0) from system gems
[...]
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
/usr/bin/ruby1.8 -I"lib:test" "/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" 
[...]
** Erubis 2.6.6
** Erubis 2.6.6
Loaded suite /usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader
Started
.............................................................................................................................................................................................................................................................................................................................................................................................................
Finished in 92.660647 seconds.

397 tests, 816 assertions, 0 failures, 0 errors
/usr/bin/ruby1.8 -I"lib:test" "/usr/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb"
Errors running test:units!
</pre>

I'm running :

```
bundle install
rake
```

as the build command.

Thanks

**Comment by botanicus** [comment]
Yup, I'm getting this as well. I'm using bundler as well, but I doubt it's the problem. It's just now showing some stuff in the test log, for some reason. Did anyone already investigate this issue? I'm stuck on it and I'd really appreciate if this could be solved, cheers.

**Comment by defunkt** [comment]
I don't understand this issue. Can you be more specific?

Whether or not your app uses Bundler should not matter to cijoe.

**Comment by gravis** [comment]
I think we can close that, since it's working now (someone may have fixed it on our CI server).
Thanks !
