### ISSUE TITLE
`rake` broken

### ISSUE THREAD

**Issue by kagminjeong** [defunkt/cijoe#24]
I'm attempting to set up cijoe and I encountered an issue. To check basic functionality of cijoe I then attempted to run the test suite, which failed:

m$ rake
(in /home/rm/apps/cijoe)
rake aborted!
Don't know how to build task 'check_dependencies'

(See full trace by running task with --trace)

**Comment by defunkt** [comment]
What version of Ruby and cijoe?

**Comment by kagminjeong** [comment]
Seems to work now. Probably fixed by https://github.com/defunkt/cijoe/commit/df0e3b66d7c173742611b27c15d8181636552ba0.
