### ISSUE TITLE
Config method_missing not working in 1.9.1

### ISSUE THREAD

**Issue by benbjohnson** [defunkt/cijoe#25]
When I run cijoe using RVM & Ruby 1.9.1 I receive the following output:

http://gist.github.com/540610

The two "No such file or directory" errors are caused by the project_path variable being passed into CIJoe::Config.new() inside CIJoe::Config.method_missing().

The fix seems to be adding a splat operator to line 4 of config.rb:

new(command, *args)

**Comment by bshaffer** [comment]
I can confirm this fixed the same issue for me when using 1.9.1

**Comment by cimm** [comment]
And I can confirm this fixed the same issue for me when using 1.9.2. :) Can this be merged, please?

**Comment by appoxy** [comment]
+1. CIJoe doesn't work in 1.9.2.

**Comment by cimm** [comment]
@appoxy Can you be a little bit more specific. I have CIJoe up and running in 1.9.2 on Ubuntu.

**Comment by hakanensari** [comment]
Encountered same problem running RVM + Ruby 1.9.2. Adding the splat operator did fix the issue.

**Comment by hakanensari** [comment]
I'm myopic. Just saw fix is already merged into the master.
