### ISSUE TITLE
Problem installing, is it a rip problem?

### ISSUE THREAD

**Issue by timothyjoh** [defunkt/cijoe#3]
Installing cijoe halts at this phrase
rip: choice requested by cijoe (0.1.0) but not found at git://github.com/defunkt/choice.git
 obvously this package exists, but rip can't get it. Also when I try to install choice via gems, it can install but that doesn't mean cijoe works. In fact it can't find the cijoe executable when I run it, but the rip package is installed. I can't reinstall rip until I uninstall it, then when I run it again, I still get the same problem with choice.

Just wanted to mention this as it may be a problem with rip as well

**Comment by defunkt** [comment]
Which version of Rip are you using? `0.0.3` is the newest and has bugfixes - sorry about putting you through the pain of all my alpha software :)

I would try uninstalling and reinstalling Rip.

**Comment by defunkt** [comment]
Did you ever get this working?

**Comment by timothyjoh** [comment]
I get this right now after uninstalling rip and reinstalling (I did only have rip 0.0.1)

version conflict!
choice requested at 8b125564 by cijoe (1a969f9)
choice previously requested at 0.1.3
rip: installation failed

**Comment by timothyjoh** [comment]
but then I uninstall choice, and reissue the install cijoe command, and everything goes smoothly. Thanks!

I don't mind trying out your alpha-ware, thanks for sharing and helping me figure out the issue.

**Comment by timothyjoh** [comment]
Sorry I forgot to close this issue

**Comment by defunkt** [comment]
Woot! Thanks for letting me know :)
