### ISSUE TITLE
Empty the ENV?

### ISSUE THREAD

**Issue by defunkt** [defunkt/cijoe#31]
Should cijoe run tests with a clean ENV, leaving it up to the test script to set everything up?

This might(?) make it more difficult to easily setup tests, but will definitely stop [unwanted environment mixups](https://github.com/blog/744-today-s-outage).

**Comment by kennethreitz** [comment]
hehehe

**Comment by dennisreimann** [comment]
+1

**Comment by gravis** [comment]
I always had issues running CIJOE, and especially with the ENV (https://github.com/defunkt/cijoe/issues#issue/23 => I suspect CIJOE tu run in production mode)
You should also never ever put your prod passwords in your repo or anywhere else than prod servers ;)

**Comment by defunkt** [comment]
Empty the ENV before building. Closed by 194ff6deb5176770ce5cad126af6f32132334796

**Comment by mcolyer** [comment]
I'm not sure this is the right fix. If you clear ENV you remove PATH and HOME which are used by various things.

Also this won't clear the environment unless you have an after-reset file. Some projects do not have an after-reset file.

**Comment by david** [comment]
I agree with mcolyer. This is totally the wrong way to do it. People should be responsible for setting up the environment cijoe runs on, it _should not_ be cijoe's responsibility to clean up the environment for them. If you want to control the environment cijoe runs in, create a new user and run cijoe as that user, or let them run cijoe with env -i.

**Comment by coverall** [comment]
This seems to only clear the environment when you have an after-reset file. Was hoping to use after-reset to run "bundle install", but it is making life difficult.
