### ISSUE TITLE
CIJoe in inittab

### ISSUE THREAD

**Issue by bshaffer** [defunkt/cijoe#33]
I have had all sorts of trouble running cijoe in inittab.  Every time I run it, whether it be with nohup, adding the ampersand on the end, or running regular, the inittab process dies with the error:

Process spawning too fast.  Killing process and respawning...

Any idea what I am doing wrong?

**Comment by kagminjeong** [comment]
You may not have a completely set up environment.

Instead of running cijoe directly try running it in a shell with output redirection, like so:

/bin/sh -c 'cijoe >/tmp/output 2>/tmp/error'

Then examine produced files for any errors.
