### ISSUE TITLE
under certain circumstances, cijoe hangs and/or leaves zombies laying around.

### ISSUE THREAD

**Issue by mlooney** [defunkt/cijoe#36]
consistently caused by suites that spin up other ruby processes (at least on 1.8.6). see my pull request for tested patch & example.

**Comment by defunkt** [comment]
what circumstances?

**Comment by MattRogish** [comment]
We've seen this as well... 

rails    12264 59.2 29.9 531576 460404 ?       S    17:45   3:29 Passenger ApplicationSpawner: /srv/cijoe   

this ruby process hangs around forever, eats up 100% CPU. Can't figure out why...
