### ISSUE TITLE
Multiple projects on the same cijoe

### ISSUE THREAD

**Issue by lsolesen** [defunkt/cijoe#39]
I would be perfect if it was possible to run multiple projects on the same port, so you do not need to startup several instances of cijoe, but could use the same cijoe for more projects.

**Comment by gravis** [comment]
it's already covered by http://chrismdp.github.com/2010/03/multiple-ci-joes-with-rack-and-passenger/ (in the readme).
we use it, it works well !

**Comment by queso** [comment]
If you guys are interested, I have a fix here that doesn't involve such complicated steps:  https://github.com/defunkt/cijoe/issues#issue/48.

**Comment by defunkt** [comment]
queso's change got merged in efc17bf4ede55bf22eed65f6c9d7a87158d834b2
