### ISSUE TITLE
doesn't work on ruby 1.9

### ISSUE THREAD

**Issue by mwotton** [defunkt/cijoe#4]
mwotton@glamdring:~/ci_projects$ cijoe Hubris
/home/mwotton/.rip/active/bin/cijoe:4:in `require': /home/mwotton/.rip/active/lib/cijoe.rb:90: formal argument cannot be an instance variable (SyntaxError)
...popen4(runner_command) do |@pid, stdin, stdout, stderr|
...                               ^
    from /home/mwotton/.rip/active/bin/cijoe:4:in`<main>'

this seems to be a common problem with the upgrade - http://www.ruby-forum.com/topic/142402

any chance of a fix?

**Comment by mwotton** [comment]
ok, i pushed a fix to my git repo. pull, s'il vous plait?

**Comment by defunkt** [comment]
Applied - thanks!
