### ISSUE TITLE
Ruby 1.9.2 issue?

### ISSUE THREAD

**Issue by stephenallred** [defunkt/cijoe#44]
Hi,

I'm getting the following error when I visit a cijoe instance running on any of my git repositories:
sh: line 0: cd: [<repo_pwd>]: No such file or directory
!! Unexpected error while processing request: undefined method `split' for nil:NilClass
where <repo_pwd> is the directory of the git repo.

Could this be to do with my ruby 1.9.2 environment? I've put some of my environment details below,

Cheers,
Steve

$ruby -v
ruby 1.9.2p0 (2010-08-18 revision 29036) [x86_64-darwin10.4.3]

$cijoe -v
/Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice/parser.rb:108: warning: Hash#index is deprecated; use Hash#key
/Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/cijoe-0.7.0/bin/cijoe:41:in `block (3 levels) in <top (required)>': uninitialized constant Choice::Option::CIJoe (NameError)
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice/parser.rb:177:in`call'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice/parser.rb:177:in `block in parse'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice/parser.rb:155:in`each'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice/parser.rb:155:in `parse'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice.rb:93:in`parse'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/choice-0.1.4/lib/choice.rb:26:in `options'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/gems/cijoe-0.7.0/bin/cijoe:6:in`<top (required)>'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/bin/cijoe:19:in `load'
    from /Users/stephenallred/.rvm/gems/ruby-1.9.2-p0/bin/cijoe:19:in`<main>'

$gem list | grep cijoe
cijoe (0.7.0)

**Comment by gma** [comment]
Hey. I had this problem yesterday and tracked it down to the way *args is dealt with at the top of config.rb. Ruby 1.9 treats arrays that are passed to method calls differently. @jbarnette patched it back in September 2010, but a new gem hasn't been released yet.

You can move on by editing `$(gem environment gemdir)/gems/cijoe-0.7.0/lib/cijoe/config.rb` and applying this patch: https://github.com/defunkt/cijoe/commit/a2c277410f0e91c9afbfc8275e8620f2b144acf9

Hopefully there'll be a new gem out soon…

**Comment by stephenallred** [comment]
Ah, cool. Cheers for the heads up!
