### ISSUE TITLE
CIJOE doesn't exit / start clean

### ISSUE THREAD

**Issue by gravis** [defunkt/cijoe#45]
We're using cijoe along with passenger (to have the "multi-project" support).
We have notices that if the web server is reload (ie : passenger reload as well), the app is restarted, leaving the current build stuck.
I think the .git/builds/current file should be removed at some point, maybe at start-up ?
thanks

**Comment by defunkt** [comment]
Use unicorn =)

**Comment by gravis** [comment]
I don't get it, sorry.
You mean that unicorn will left the child process when cijoe is restarted ?
What if this child is stuck ? Unicorn will just lead to zombie processes ?
I think cijoe should REALLY cleanup state at startup, having a current build (ie: .git/builds/current) ongoing at startup doesn't make any sense, and will stuck cijoe for later builds :(

**Comment by dblock** [comment]
+1 cijoe could notice .git/builds/current on startup, check the pid and mark the build as failed
