### ISSUE TITLE
$? is nil

### ISSUE THREAD

**Issue by brentgreeff** [defunkt/cijoe#50]
For some reason I am getting an exception
at the end of the build.

$?.exitstatus

is breaking because $? is nil,
not sure why this would happen?

**Comment by queso** [comment]
brentgreeff,

Could you share your build command with us?  My guess is that the process is crashing before exit.  I would have to dig into Process.waitpid and exitstatus more, but that is my first hunch.

**Comment by brentgreeff** [comment]
Hi, sorry for the delay

"rake spec RAILS_ENV=test"

This works fine locally, but on debian there was an issue,
I think its an environment based.

Hudson has been installed in the mean time.

I can fork this and improve the error message if you think its worthwhile?

**Comment by brentgreeff** [comment]
I did not mean to close this,
Cant get hudson working with campfire,
so would be good to get some insight into this.

**Comment by mculp** [comment]
I changed Process.waitpid(...) to Process.wait, which fixed this issue for me. Any reason why I shouldn't do that?
