### ISSUE TITLE
Campfire section of the Readme needs updating

### ISSUE THREAD

**Issue by erunion** [defunkt/cijoe#52]
It's still referring to using a password when using Campfire, but you actually now (and as reflected in campfire.rb) need to use an API token instead. Should save a few headaches.

**Comment by queso** [comment]
I updated the readme, here: https://github.com/queso/cijoe/commit/cbd3e638d2578c71aaa7129a2261f286b063a769

I am just waiting on defunkt to merge it.

**Comment by queso** [comment]
This has been merged: 3ffcbbd89b7c931641388e5ed7e8654638d91a08.
