### ISSUE TITLE
Timeout for long running set of specs

### ISSUE THREAD

**Issue by edsinclair** [defunkt/cijoe#6]
I set up ci joe for two different rails apps. It works flawlessly for the smaller of the two. For the larger app it consistently times out after ~ 1000 seconds. CI Joe is running behind nginx and using Thin 1.2.4 Any suggestions on where I should be trying to boost a timeout setting?

Thanks very much for such a simple and easy to set up CI server. Congrats on the rackspace move as well.

**Comment by edsinclair** [comment]
Did some further tests to try to isolate the timeout issue. Issue is consistent when switching to mongrel 1.1.5 and when making 'Build' POST to localhost:4567, so it doesn't seem to be nginx or thin. The test.log just stops abruptly after a SQL ROLLBACK entry... The rake spec process is still around, so maybe it is a MySQL issue that doesn't occur when I run rake spec from the command line?

**Comment by edsinclair** [comment]
Okay further digging reveals that the timeout is happening somewhere in Open4.popen4() And is likely due to the enormous amount of stdout created by rspec's specdoc format... Closing this, but hopefully these notes may be of use to someone else.

**Comment by defunkt** [comment]
Were you able to fix it, or did you give up?

**Comment by efficiency20** [comment]
Unfortunately, I don't have the time to dig further into how open4 handles stdout. Our project needed CI too badly for me to spend any more time on it right now. I ended up setting up CruiseControl.rb, which has it's own issues, but it is working. I'm pretty sure the open4 issue is probably related to a bug that is mentioned in the open4 0.8.0 changelog entry. It should be pretty easy to replicate the issue on a large spec suite using the specdoc output option.

Thanks
