### ISSUE TITLE
CI Joe error

### ISSUE THREAD

**Issue by suriyaa** [defunkt/cijoe#84]
Hi guys, :smile: 

I got today a "**:public is no longer used to avoid overloading Module#public, use:public_folder or :public_dir instead**" _error_:

![screenshot 2015-04-19 12 01 25](https://cloud.githubusercontent.com/assets/5073946/7219634/2d898c28-e6a9-11e4-93d9-998d89930108.png)

There are many other persons with the same problem: #72, #75, #82.

_What's the problem of CI Joe?_

Yours,
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat:

**Comment by suriyaa** [comment]
@defunkt

**Comment by suriyaa** [comment]
@defunkt / @rtomayko @queso @threedaymonk @tmm1 @cmw @phuesler @simpsonjulian @shingara @koppen @jbarnette @gotascii @antono @rsanheim @cmeiklejohn @tobi @adamstrickland @croaky @jkamenik @rcarver @adonaldson @brycethornton @fritzek @vjt @dcrec1 @hpoydar

---

I'm still waiting for an answer.

**Comment by adonaldson** [comment]
Hi there, the last commit to this repo was 2011 and the description is 'unmaintained'.

Given the lack of active maintainers (as you've experienced, waiting nearly a year for a response is commitment to say the least), I'd recommending checking out a copy of the code and digging into the problem yourself and submitting a PR.

Actually, I'd suggest perhaps investigating more up to date alternatives, this page may have some:
https://www.ruby-toolbox.com/categories/continuous_integration

Also, I'm not sure notifying everyone by name is the best way to get a positive response.

Hope this helps!

Andrew
